@baseUrl = http://localhost:8000

### 
POST {{baseUrl}}/api/addQuestion
Content-Type: application/json; charset=utf-8

{
   "title": "1+1=?",
   "options": [
      {
         "label": "1",
         "status": true
      },
      {
         "label": "2",
         "status": true
      },
      {
         "label": "3",
         "status": false
      },
      {
         "label": "4",
         "status": false
      }
   ]
}

###

POST {{baseUrl}}/api/updateQuestion
Content-Type: application/json; charset=utf-8

{
   "id": 2,
   "title": "2+2=?",
   "options": [
      {
         "label": "1",
         "status": false
      },
      {
         "label": "2",
         "status": true
      },
      {
         "label": "3",
         "status": false
      },
      {
         "label": "4",
         "status": false
      }
   ]
}
###

POST {{baseUrl}}/api/getQuestion
Content-Type: application/json; charset=utf-8

{
   "id": 2
}


###

POST {{baseUrl}}/api/getQuestion
Content-Type: application/json; charset=utf-8

{
   "id": 2
}


###

POST {{baseUrl}}/api/removeQuestion
Content-Type: application/json; charset=utf-8

{
   "id": 1
}


###

POST {{baseUrl}}/api/getQuestionList
Content-Type: application/json; charset=utf-8

{
   "page": 1,
   "size": 1
}

###
POST {{baseUrl}}/api/updateQuestionAnswerResult
Content-Type: application/json; charset=utf-8

{
   "id": 2,
   "result": true
}


###
POST {{baseUrl}}/api/updateQuestionAnswerResult
Content-Type: application/json; charset=utf-8

{
   "id": 2,
   "result": false
}